name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: git-changelog
          path: target/x86_64-unknown-linux-gnu/release/git-changelog
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/x86_64-unknown-linux-gnu/release/git-changelog