name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        profile: minimal

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: cli-linux
        path: target/x86_64-unknown-linux-gnu/release/git-changelog