name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: cli-linux
          path: target/x86_64-unknown-linux-gnu/release/git-changelog
